version: '3.8'
services:
  postgres:
    image: postgres:15.3
    container_name: Strip-Postgres-DB
    restart: always
    ports:
      - "8089:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strip-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: